# Site
name: Sool.K Blog
description: 지극히 개인적인 글정리를 목적으로 한 블로그입니다. 다만 어느 시점, 어떤 곳의 누군가에게는 도움이 될 수 있기를 바랍니다. 미래의 나를 포함해서.
meta_description: "Jekyll theme for blogging."
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/favicon.jpg'
paginate: 12
baseurl:
email: 'kinchi22@gmail.com'
google_analytics: 'UA-134155584-1'
disqus: 'demowebsite'
sharethis: '<script async src="//platform-api.sharethis.com/js/sharethis.js#property=5c5d06106dbc680011d2b568&product="sticky-share-buttons"></script>'

# Authors
authors:
  sk:
    name: Seulki Bae
    display_name: Seulki Bae
    gravatar: d2efe0379732ea1432545bfaf95001db
    email: kinchi22@gmail.com
    web: https://kinchi22.github.io
    description: "Auther of this blog. Interested in movie and programming especially HPC, AI and web application."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Other
markdown: kramdown
highlighter: rouge